---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo-workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-rb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: executor
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo-workflows