apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher-rb
  namespace: pottmeier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watcher
subjects:
- kind: ServiceAccount
  name: watcher
  namespace: argo-events
