apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher
  namespace: pottmeier
rules:
- apiGroups:
  - pottmeier.de
  resources:
  - specials
  - special
  verbs:
  - get
  - list
  - watch
