---
publicDomain: s3.example.com
ui:
  enabled: true
  publicDomain: s3-ui.example.com
ingress:
  enabled: true
storageClass:
  name: local
  create: true
  local: true
  localPath: /tmp/local-storage
