---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: employee-sensor
spec:
  dependencies:
    - name: employee-add-dep
      eventSourceName: employee-eventsource
      eventName: employee-add
    - name: employee-del-dep
      eventSourceName: employee-eventsource
      eventName: employee-delete
    - name: employee-upd-dep
      eventSourceName: employee-eventsource
      eventName: employee-update
  triggers:
    - template:
        name: http-trigger-add
        http:
          url: http://dbrest-db2rest:8080/v1/rdbms/db/employee 
          payload:
            - src:
                dependencyName: employee-add-dep
                dataKey: body.id
              dest: id
            - src:
                dependencyName: employee-add-dep
                dataKey: body.first_name
              dest: first_name
            - src:
                dependencyName: employee-add-dep
                dataKey: body.last_name
              dest: last_name
            - src:
                dependencyName: employee-add-dep
                dataKey: body.email
              dest: email
            - src:
                dependencyName: employee-add-dep
                dataKey: body.created_on
              dest: created_on
          method: POST
    - template:
        name: http-trigger-del
        http:
          url: http://dbrest-db2rest:8080/v1/rdbms/db/employee 
          payload:
            - src:
                dependencyName: employee-del-dep
              dest: type
          method: DELETE
    - template:
        name: http-trigger-upd
        http:
          url: http://dbrest-db2rest:8080/v1/rdbms/db/employee&filter=id==1
          payload:
            - src:
                dependencyName: employee-upd-dep
                dataKey: body.id
              dest: id
            - src:
                dependencyName: employee-upd-dep
                dataKey: body.first_name
              dest: first_name
            - src:
                dependencyName: upd-add-dep
                dataKey: body.last_name
              dest: last_name
            - src:
                dependencyName: upd-add-dep
                dataKey: body.email
              dest: email
            - src:
                dependencyName: employee-upd-dep
                dataKey: body.created_on
              dest: created_on
          method: PUT
      retryStrategy:
        steps: 3
        duration: 3s