apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher
  namespace: gitops-bridge
rules:
- apiGroups:
  - pottmeier.de
  resources:
  - employees
  - employee
  verbs:
  - get
  - list
  - watch
