---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3gw.configMap" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4}}
data:
{{- if .Values.ui.enabled }}
{{- if or .Values.useCertManager .Values.tls.publicDomain.crt }}
  S3GW_SERVICE_URL: 'https://{{ include "s3gw.serviceName" . }}.{{ .Values.publicDomain }}'
{{- else}}
  S3GW_SERVICE_URL: 'http://{{ include "s3gw.serviceName" . }}.{{ .Values.publicDomain }}'
{{- end }}
{{- end }}
