{{- if .Values.cosi.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3gw-cosi.ServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "s3gw.labels" . | indent 4 }}
{{- end }}
