---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kube-api
spec:
  eventBusName: default
  template:
   serviceAccountName: evt-sa
  resource:
    nsevent:
      version: v1
      resource: namespaces
      eventTypes: [ ADD, DELETE, UPDATE ]
#      filter:
#        fields:
#        - key: metadata.annotations.autodeploy-ingress-host
#          operation: =
#          value: ".+"
#---
#apiVersion: argoproj.io/v1alpha1
#kind: EventSource
#metadata:
#  name: kube-api
#  namespace: argo-events
#spec:
#  eventBusName: default
#  template:
#    serviceAccountName: evt-sa
#    spec:
#      containers:
#        - name: main
#          image: argoproj/argo-events:latest
#  resources:
#    kubernetes:
#      namespace-change:
#        namespace: default
#        eventTypes:
#          - add
#          - update
#         - delete
#        resource:
#          apiVersion: v1
#          kind: Namespace
