---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: kube-api
spec:
  eventBusName: default
  template:
   serviceAccountName: evt-sa
  resource:
    ingress:
#      namespace: playground
      group: ""
      version: v1
      resource: namespaces
      eventTypes: [ ADD, DELETE, UPDATE ]
#      filter:
#        fields:
#        - key: metadata.annotations.autodeploy-ingress-host
#          operation: =
#          value: ".+"