---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: ingress-sn
 
spec:
  eventBusName: default
  template:
    serviceAccountName: evt-sa
  dependencies:
  - name: kube
    eventSourceName: kube-api
    eventName: nsevent
  triggers:
  - template:
        name: http-trigger
        http:
          #url: http://httpbin/post
          url: http://logger-simple-http-logger:8080
          payload:
            - src:
                dependencyName: kube
                dataKey: body.metadata.name
              dest: namespace
          method: POST
    #retryStrategy:
    #    steps: 3
    #    duration: 3s      
  - template:
      name: logging
      log:
        intervalSeconds: 15